[package]
name = "findutils"
version = "0.1.0"
authors = ["mcharsley <mcharsley@google.com>"]

[dependencies]
glob = "0.3"
# Current release of walkdir doesn't support depth-first operation. While we 
# wait for https://github.com/BurntSushi/walkdir/pull/19 to be accepted and a
# new release made, let's access my branch directly.
walkdir = "2.2"
tempdir = "0.3"
regex = "1.1"

[[bin]]
name = "find"
path = "src/find/main.rs"

[[bin]]
name = "testing-commandline"
path = "src/testing/commandline/main.rs"
